### ISSUE TITLE
Frontend directory?

### ISSUE THREAD

**Issue by nicolerg** [lidaof/eg-docs#15]
Hello, I am trying to follow the documentation to upload a custom genome [here](https://buildmedia.readthedocs.org/media/pdf/epigenomegateway/latest/epigenomegateway.pdf). In Step 6.1, I installed NodeJS. In Step 6.2, it says to enter the `frontend` directory, but I cannot find the path to `frontend`. It is not in the NodeJS installation, and I don't see it as a folder in the WashU EG [source code](https://github.com/epgg/eg). Can you please clarify what path you're referring to? Do I need a specific version of NodeJS?

**Comment by lidaof** [comment]
Hi @nicolerg , sorry for confusion. repository is here: https://github.com/lidaof/eg-react

**Comment by nicolerg** [comment]
Thank you for the clarification! I appreciate the quick response.
